FORMAT: 1A
HOST: localhost/api/

# mithuntantri

An API written in golang allowing consumers to view polls and vote in them.

## Sign Up [/signup]

### Using Mobile Number [POST]

+ Request (application/json)

        {
            "mobileno": "8867742253"
        }
        
+ Response 200 (application/json)

        {
            "data":{
                "is_newUser": true
            },
            "message":"",
            "status":"success"
        }

## Login [/login]
    
### Using Facebook Signup [POST]

+ Request (application/json)
        
        {
            "login_type":1
        }

+ Response 200 (application/json)